name: Update Files

on: [push]

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Check for non-README changes
      id: check-changes
      run: |
        non_readme_changes=false
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ "$file" != *"README.md" ]]; then
            non_readme_changes=true
            break
          fi
        done
        echo "non_readme_changes=$non_readme_changes" >> $GITHUB_OUTPUT

    - name: Update files
      if: steps.check-changes.outputs.non_readme_changes == 'true'
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ "$file" != *"README.md" ]]; then
            echo "Traitement du fichier $file"
            # Ajoutez ici le code pour traiter les fichiers non-README
            # Par exemple :
            # echo "Cette ligne a été ajoutée par GitHub Actions" >> "$file"
          fi
        done

    - name: Commit changes
      if: steps.check-changes.outputs.non_readme_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour automatique des fichiers (hors README)"
        git push