name: Update README

on:
  push:
    paths:
      - './1er%20Semestre/R114/'
      - '/1er%20Semestre/R115/'
      - '/2nd%20Semestre/R110/'
      # Ajoutez d'autres dossiers selon vos besoins

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Update README
        run: |
          # Définir les dossiers à surveiller
          WATCHED_FOLDERS=("dossier1" "dossier2" "dossier3")
          
          # Obtenir la liste des fichiers modifiés dans les dossiers surveillés
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E "^($(IFS=\|; echo "${WATCHED_FOLDERS[*]}"))/")
          
          # Vérifier s'il y a des fichiers modifiés
          if [ -n "$FILES" ]; then
            echo "## Fichiers mis à jour" >> temp_readme.md
            
            # Pour chaque fichier modifié
            while IFS= read -r FILE; do
              # Ajouter le lien relatif au fichier temporaire
              echo "- [$FILE]($FILE)" >> temp_readme.md
            done <<< "$FILES"
            
            # Ajouter le contenu du fichier temporaire au README existant
            cat README.md temp_readme.md > new_readme.md
            mv new_readme.md README.md
            rm temp_readme.md
          else
            echo "Aucun fichier modifié dans les dossiers surveillés."
          fi
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Mise à jour automatique du README" || echo "Pas de changements à commiter"
          git push
