name: Update Files

on: [push]

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git encoding
      run: |
        git config --global core.quotePath false
        git config --global core.precomposeunicode true

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        separator: "|"
        escape_json: 'false'

    - name: Check for changed files
      id: check-changes
      run: |
        Fichier=()
        
        input_string=$"${{ steps.changed-files.outputs.all_changed_files }}"
        echo "$input_string"
        
        decode_special_chars() {
          echo "$1" | sed 's/\\303\\240/à/g; s/\\303\\250/è/g; s/\\303\\251/é/g; s/\\303\\252/ê/g; s/\\303\\256/î/g; s/\\303\\264/ô/g; s/\\303\\271/ù/g'
        }

        while IFS= read -r -d '|' file; do
          decoded_file=$(decode_special_chars "$file")
          decoded_file=$(printf '%b' "$decoded_file")
          
          if [[ "$decoded_file" != *"README.md" && "$decoded_file" == *"1er Semestre/"* ]]; then
            Fichier+=("$decoded_file")
          fi
        done <<< "${input_string}|"
        
        if [ ${#Fichier[@]} -gt 0 ]; then
          echo "Tous les fichiers détectés :"
          for f in "${Fichier[@]}"; do
            printf '%s\n' "$f"
          done
        else
          echo "Aucun fichier détecté."
        fi


    # - name: Commit changes
    #   if: 
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour automatique des fichiers (hors README)"
    #     git push


# Ajout du fait qu'il n'execute pas si les premier dossier ne sont pas dans 1er semestre, etc
# Faire une boucle pour traiter les fichiers
# verifier si il y a bien un fichier README dans le dossier parent
# mettre le lien dans la bonne ligne (CM, TD, TP)
