name: Detect Changed Files

on: [push]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Print changed files
      run: |
        echo "Les fichiers modifiés sont :"
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file"
        done