name: Update Files

on: [push]

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Check for changed files
      id: check-changes
      run: |
        Fichier=()

        # Simuler l'entrée des fichiers pour le test
        all_changed_files=".github/workflows/update-readme.yml 1er Semestre/R114/TD/README.md 1er Semestre/R115/TD/COURS Gestion de projet cascade ETU.pdf"

        # Lire tous les fichiers dans un tableau en utilisant le bon format
        # Utiliser 'printf' pour gérer les espaces correctement
        while IFS= read -r file; do
            # Vérifie si le fichier n'est pas README.md et qu'il est dans le répertoire 1er Semestre/
            if [[ "$file" != *"README.md" && "$file" == *"1er Semestre/"* ]]; then
                Fichier+=("$file")
                echo "Fichier détecté : $file"
            fi
        done < <(printf '%s\n' $all_changed_files)

        if [ ${#Fichier[@]} -gt 0 ]; then
            echo "Total de fichiers détectés : ${#Fichier[@]}"
            for f in "${Fichier[@]}"; do
                echo "$f"
            done
        else
            echo "Aucun fichier détecté."
        fi


    # - name: Commit changes
    #   if: 
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour automatique des fichiers (hors README)"
    #     git push


# Ajout du fait qu'il n'execute pas si les premier dossier ne sont pas dans 1er semestre, etc
# Faire une boucle pour traiter les fichiers
# verifier si il y a bien un fichier README dans le dossier parent
# mettre le lien dans la bonne ligne (CM, TD, TP)
