name: Update Files

# on:
#   schedule:
#     - cron: '0 12 * * 5'

on:
  push:
    branches:
      - main

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get all files in 1er Semestre
      id: get-files
      run: |
        files=$(find ./1er\ Semestre -type f)
        echo "all_files<<EOF" >> $GITHUB_OUTPUT
        echo "$files" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Process files and create README.md
      id: process-files
      shell: bash
      run: |
        set +e  # Désactive la sortie immédiate en cas d'erreur
        declare -A FilesByDirAndType
        NonR1Files=()
        
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            if [[ "$file" =~ /1er\ Semestre/(R1[0-9]{2})/(CM|TD|TP)/ ]]; then
              parent_dir=${BASH_REMATCH[1]}
              file_type=${BASH_REMATCH[2]}
              FilesByDirAndType["$parent_dir,$file_type"]+="$file"$'\n'
            elif [[ "$file" =~ /1er\ Semestre/(R1[0-9]{2})/ ]]; then
              parent_dir=${BASH_REMATCH[1]}
              FilesByDirAndType["$parent_dir,Autres"]+="$file"$'\n'
            else
              NonR1Files+=("$file")
            fi
          else
            echo "Avertissement : Le fichier $file n'existe pas ou n'est pas accessible."
          fi
        done <<< "${{ steps.get-files.outputs.all_files }}"
        
        total_count=0
        current_dir=""
        for key in $(echo "${!FilesByDirAndType[@]}" | tr ' ' '\n' | sort); do
          IFS=',' read -r dir type <<< "$key"
          if [[ "$dir" != "$current_dir" ]]; then
            [[ -n "$current_dir" ]] && echo ""
            echo "Fichiers dans /$dir/"
            current_dir="$dir"
            
            # Création du fichier README.md
            readme_path="./1er Semestre/$dir/README.md"
            echo "# Ressources pour $dir" > "$readme_path"
            echo "" >> "$readme_path"
            echo "Ce répertoire contient les ressources pour le module $dir." >> "$readme_path"
            echo "" >> "$readme_path"
            echo "## Structure du répertoire" >> "$readme_path"
            echo "" >> "$readme_path"
            echo "- CM : Cours magistraux" >> "$readme_path"
            echo "- TD : Travaux dirigés" >> "$readme_path"
            echo "- TP : Travaux pratiques" >> "$readme_path"
            echo "- Autres : Ressources supplémentaires" >> "$readme_path"
            echo "" >> "$readme_path"
            echo "## Contenu" >> "$readme_path"
            echo "" >> "$readme_path"
          fi
          echo "  $type:" | tee -a "$readme_path"
          while IFS= read -r file; do
            echo "    $file"
            echo "- $(basename "$file")" >> "$readme_path"
            ((total_count++))
          done <<< "${FilesByDirAndType[$key]}"
          echo "" >> "$readme_path"
        done
        
        echo "fichier_count=$total_count" >> $GITHUB_OUTPUT 
        
        if [ ${#NonR1Files[@]} -gt 0 ]; then
          echo "Fichiers hors des répertoires R1** :"
          printf '%s\n' "${NonR1Files[@]}"
        fi
        
        echo "Nombre total de fichiers traités : $total_count"

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        if git diff --staged --quiet; then
          echo "Aucun changement à commiter"
        else
          git commit -m "Mise à jour des fichiers README.md"
          echo "Changements commités"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}