name: Detect Changed Files

on:
  push:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: get_changed_files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD > changed_files.txt
          cat changed_files.txt
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Display changed files
        run: |
          echo "Les fichiers changés sont :"
          echo "${{ steps.get_changed_files.outputs.files }}"