name: Update Files

on: [push]

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Configure Git encoding
      run: git config --global core.quotePath false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        separator: "|"
        escape_json: 'false'

    - name: Process changed files
      run: |
        echo "Changed files:"
        IFS='|' read -ra CHANGED_FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
        for file in "${CHANGED_FILES[@]}"; do
          echo "  - $file"
        done

    - name: Display file contents (example)
      run: |
        IFS='|' read -ra CHANGED_FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
        for file in "${CHANGED_FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "Contents of $file:"
            cat "$file"
            echo "------------------------"
          fi
        done

    - name: Example processing with special characters
      run: |
        IFS='|' read -ra CHANGED_FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
        for file in "${CHANGED_FILES[@]}"; do
          filename=$(basename "$file")
          echo "Processing file: $filename"
          # Add your processing logic here
          # For example, you could rename the file:
          # mv "$file" "${file}_processed"
        done


    # - name: Commit changes
    #   if: 
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour automatique des fichiers (hors README)"
    #     git push


# Ajout du fait qu'il n'execute pas si les premier dossier ne sont pas dans 1er semestre, etc
# Faire une boucle pour traiter les fichiers
# verifier si il y a bien un fichier README dans le dossier parent
# mettre le lien dans la bonne ligne (CM, TD, TP)
